POST http://localhost:3000/weekly_reflection
Content-Type: application/json

{
  "user_id": "123",
  "feeling": "good",
  "pastWeek": "good",
  "feedbackOnWeeklyPlan": "good"
}

### Test GET Request
curl -X POST http://localhost:3000/planner \
-H "Content-Type: application/json" \
-d '{
  "Sunday": {
    "Breakfast": { "meal": "coffee", "meal_id": "123" },
    "Lunch": { "meal": "hamburger", "meal_id": "123" },
    "Dinner": { "meal": "soup", "meal_id": "123" }
  },
  "Monday": {
    "Breakfast": { "meal": "coffee", "meal_id": "123" },
    "Lunch": { "meal": "hamburger", "meal_id": "123" },
    "Dinner": { "meal": "soup", "meal_id": "123" }
  },
  "Tuesday": {
    "Breakfast": { "meal": "coffee", "meal_id": "123" },
    "Lunch": { "meal": "hamburger", "meal_id": "123" },
    "Dinner": { "meal": "soup", "meal_id": "123" }
  },
  "Wednesday": {
    "Breakfast": { "meal": "coffee", "meal_id": "123" },
    "Lunch": { "meal": "hamburger", "meal_id": "123" },
    "Dinner": { "meal": "soup", "meal_id": "123" }
  },
  "Thursday": {
    "Breakfast": { "meal": "coffee", "meal_id": "123" },
    "Lunch": { "meal": "hamburger", "meal_id": "123" },
    "Dinner": { "meal": "soup", "meal_id": "123" }
  },
  "Friday": {
    "Breakfast": { "meal": "coffee", "meal_id": "123" },
    "Lunch": { "meal": "hamburger", "meal_id": "123" },
    "Dinner": { "meal": "soup", "meal_id": "123" }
  },
  "Saturday": {
    "Breakfast": { "meal": "coffee", "meal_id": "123" },
    "Lunch": { "meal": "hamburger", "meal_id": "123" },
    "Dinner": { "meal": "soup", "meal_id": "123" }
  },
  "user_id": "1234"
}'

# ###
GET http://localhost:3000/planner/1234


# ###

###
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "123",
  "email": "good",
  "password": "good"
}

###

###
GET http://localhost:3000/user/669a709b3fa640cc5886aba4
###

###
GET http://localhost:3000/user
###

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "myUserEmail!!!!@gmail.com",
  "password": "myPassword123456",
  "name": "Lior"
}
###