POST http://localhost:3000/api/weekly_reflection
Content-Type: application/json

{
  "user_id": "123",
  "feeling": "good",
  "pastWeek": "good",
  "feedbackOnWeeklyPlan": "good"
}

### Test GET Request
GET http://localhost:3000/api/weekly_reflection

### Create a new planner
POST http://localhost:3000/api/planner
Content-Type: application/json

{
  "user_id": "1234",
  "sunday": {
    "breakfast": ["eggs", "bacon"],
    "lunch": ["salad", "chicken"],
    "dinner": ["pasta"]
  },
  "monday": {
    "breakfast": ["cereal"],
    "lunch": ["sandwich"],
    "dinner": ["steak", "potatoes"]
  },
  "tuesday": {
    "breakfast": ["pancakes"],
    "lunch": ["burger"],
    "dinner": ["fish", "rice"]
  },
  "wednesday": {
    "breakfast": ["toast"],
    "lunch": ["soup"],
    "dinner": ["chicken", "veggies"]
  },
  "thursday": {
    "breakfast": ["yogurt"],
    "lunch": ["tacos"],
    "dinner": ["pizza"]
  },
  "friday": {
    "breakfast": ["smoothie"],
    "lunch": ["wrap"],
    "dinner": ["lasagna"]
  },
  "saturday": {
    "breakfast": ["waffles"],
    "lunch": ["salmon"],
    "dinner": ["stir-fry"]
  }
}
### Retrieve the planner for user 123
GET http://localhost:3000/api/planner/1234

###